const HISTORY_KEY = 'freshdraw.history.v1';
const MAX_HISTORY = 10;
const ATTEMPT_CAP = 10000; // guards against an exhausted pool; never reached in practice

const el = {
  balls: document.getElementById('balls'),
  placeholder: document.getElementById('placeholder'),
  generate: document.getElementById('generate'),
  readout: document.getElementById('readout'),
  dataBadge: document.getElementById('dataBadge'),
  dataProvenance: document.getElementById('dataProvenance'),
  historyPanel: document.getElementById('historyPanel'),
  history: document.getElementById('history'),
  clearHistory: document.getElementById('clearHistory'),
  offline: document.getElementById('offline'),
  spaceSize: document.getElementById('spaceSize'),
  excludedShare: document.getElementById('excludedShare'),
  oddsBefore: document.getElementById('oddsBefore'),
  oddsAfter: document.getElementById('oddsAfter'),
};

const nz = new Intl.NumberFormat('en-NZ');

let config = null;
let excluded = null; // Set of canonical keys, e.g. "3-11-19-24-31-38"
let history = loadHistory();

/* ---------- randomness ---------- */

// Rejection sampling on the browser's CSPRNG. A plain `% max` would bias the
// low end of the range, since 2^32 is not a multiple of 40.
function randomInt(max) {
  const limit = Math.floor(0xffffffff / max) * max;
  const buf = new Uint32Array(1);
  let value;
  do {
    crypto.getRandomValues(buf);
    value = buf[0];
  } while (value >= limit);
  return (value % max) + 1;
}

function drawNumbers(count, pool) {
  const picked = new Set();
  while (picked.size < count) picked.add(randomInt(pool));
  return [...picked].sort((a, b) => a - b);
}

/* ---------- exclusion ---------- */

const canonical = (numbers) => numbers.join('-');

function generateLine() {
  for (let attempt = 1; attempt <= ATTEMPT_CAP; attempt++) {
    const numbers = drawNumbers(config.mainCount, config.mainPool);
    if (!excluded.has(canonical(numbers))) {
      return { numbers, powerball: randomInt(config.powerballPool), attempts: attempt };
    }
  }
  throw new Error('Could not find an unused combination within the attempt cap.');
}

/* ---------- maths for the honesty panel ---------- */

function combinations(n, k) {
  let result = 1;
  for (let i = 1; i <= k; i++) result = (result * (n - k + i)) / i;
  return Math.round(result);
}

function describeOdds() {
  const total = combinations(config.mainPool, config.mainCount);
  const remaining = total - excluded.size;
  const share = (excluded.size / total) * 100;

  el.spaceSize.textContent = nz.format(total);
  el.excludedShare.textContent = `${nz.format(excluded.size)} of them (${share.toFixed(3)}%)`;
  el.oddsBefore.textContent = `1 in ${nz.format(total)}`;
  el.oddsAfter.textContent = `1 in ${nz.format(remaining)}`;
}

/* ---------- rendering ---------- */

function renderLine({ numbers, powerball }) {
  // Main numbers and Powerball go on separate rows deliberately. Seven balls on
  // one row wraps unevenly on a phone; this reads the same at any width.
  const main = document.createElement('div');
  main.className = 'row main';
  main.append(...numbers.map((n, i) => ball(n, i)));

  const power = document.createElement('div');
  power.className = 'row power';
  power.append(ball(powerball, numbers.length, true));

  el.balls.replaceChildren(main, power);
}

function ball(value, index, isPowerball = false) {
  const node = document.createElement('span');
  node.className = isPowerball ? 'ball pb' : 'ball';
  node.textContent = value;
  node.style.animationDelay = `${index * 40}ms`;
  if (isPowerball) node.setAttribute('aria-label', `Powerball ${value}`);
  return node;
}

function renderReadout({ attempts }) {
  const checked = `Checked against ${nz.format(excluded.size)} past draws`;
  const redraws =
    attempts === 1
      ? 'first line was unused'
      : `redrawn ${attempts - 1} ${attempts === 2 ? 'time' : 'times'} to avoid a past winner`;
  el.readout.textContent = `${checked} — ${redraws}.`;
}

function renderHistory() {
  el.historyPanel.hidden = history.length === 0;
  el.history.replaceChildren(
    ...history.map((entry) => {
      const li = document.createElement('li');
      const line = document.createElement('span');
      line.className = 'line';
      line.textContent = entry.numbers.join('  ');
      const pb = document.createElement('span');
      pb.className = 'pb';
      pb.textContent = `PB ${entry.powerball}`;
      li.append(line, pb);
      return li;
    }),
  );
}

function renderDataBadge() {
  el.dataProvenance.textContent = config.synthetic
    ? `The comparison set is currently ${nz.format(excluded.size)} placeholder draws generated by tools/generate-synthetic-draws.mjs — the right shape and size for real NZ Lotto history, but not real results. Swapping in real data means replacing data/draws.json; no other code changes.`
    : `The comparison set is ${nz.format(excluded.size)} real draws, ${config.firstDraw} to ${config.lastDraw}.`;

  if (!config.synthetic) return;
  el.dataBadge.hidden = false;
  el.dataBadge.textContent =
    'Using placeholder draw data — the numbers below are generated correctly, but the "already won" set is synthetic, not real NZ Lotto history.';
}

/* ---------- history persistence ---------- */

function loadHistory() {
  try {
    const raw = localStorage.getItem(HISTORY_KEY);
    return raw ? JSON.parse(raw) : [];
  } catch {
    return []; // private mode, or a stale shape from an older version
  }
}

function saveHistory() {
  try {
    localStorage.setItem(HISTORY_KEY, JSON.stringify(history));
  } catch {
    /* not worth interrupting the user over */
  }
}

/* ---------- wiring ---------- */

function onGenerate() {
  let line;
  try {
    line = generateLine();
  } catch (error) {
    el.readout.textContent = error.message;
    return;
  }

  el.placeholder?.remove();
  renderLine(line);
  renderReadout(line);

  history = [{ numbers: line.numbers, powerball: line.powerball }, ...history].slice(0, MAX_HISTORY);
  saveHistory();
  renderHistory();
}

async function init() {
  renderHistory();

  try {
    const response = await fetch('./data/draws.json');
    if (!response.ok) throw new Error(`HTTP ${response.status}`);
    const payload = await response.json();

    config = payload.meta;
    excluded = new Set(payload.draws.map((draw) => canonical(draw.numbers)));

    describeOdds();
    renderDataBadge();

    el.generate.disabled = false;
    el.generate.textContent = 'Generate a line';
    el.generate.addEventListener('click', onGenerate);
  } catch (error) {
    el.generate.textContent = 'Draw data unavailable';
    el.readout.textContent = `Could not load the past-draw set (${error.message}). Generating without it would defeat the point, so the button stays disabled.`;
  }

  el.clearHistory.addEventListener('click', () => {
    history = [];
    saveHistory();
    renderHistory();
  });

  const showOffline = () => {
    el.offline.hidden = navigator.onLine;
  };
  addEventListener('online', showOffline);
  addEventListener('offline', showOffline);
  showOffline();

  if ('serviceWorker' in navigator) {
    // Relative path so the scope follows the deploy path — this app is served
    // from a subdirectory on GitHub Pages, not a domain root.
    navigator.serviceWorker.register('./sw.js').catch(() => {
      /* app works fine without offline support */
    });
  }
}

init();
