const HISTORY_KEY = 'freshdraw.history.v1';
const MAX_HISTORY = 10;
const ATTEMPT_CAP = 10000; // guards against an exhausted pool; never reached in practice

const el = {
  balls: document.getElementById('balls'),
  placeholder: document.getElementById('placeholder'),
  generate: document.getElementById('generate'),
  readout: document.getElementById('readout'),
  dataBadge: document.getElementById('dataBadge'),
  dataProvenance: document.getElementById('dataProvenance'),
  funFacts: document.getElementById('funFacts'),
  factsSource: document.getElementById('factsSource'),
  historyPanel: document.getElementById('historyPanel'),
  history: document.getElementById('history'),
  clearHistory: document.getElementById('clearHistory'),
  offline: document.getElementById('offline'),
  spaceSize: document.getElementById('spaceSize'),
  excludedShare: document.getElementById('excludedShare'),
  oddsBefore: document.getElementById('oddsBefore'),
  oddsAfter: document.getElementById('oddsAfter'),
};

const nz = new Intl.NumberFormat('en-NZ');

let config = null;
let excluded = null; // Set of canonical keys, e.g. "3-11-19-24-31-38"
let history = loadHistory();

/* ---------- randomness ---------- */

// Rejection sampling on the browser's CSPRNG. A plain `% max` would bias the
// low end of the range, since 2^32 is not a multiple of 40.
function randomInt(max) {
  const limit = Math.floor(0xffffffff / max) * max;
  const buf = new Uint32Array(1);
  let value;
  do {
    crypto.getRandomValues(buf);
    value = buf[0];
  } while (value >= limit);
  return (value % max) + 1;
}

function drawNumbers(count, pool) {
  const picked = new Set();
  while (picked.size < count) picked.add(randomInt(pool));
  return [...picked].sort((a, b) => a - b);
}

/* ---------- exclusion ---------- */

const canonical = (numbers) => numbers.join('-');

function generateLine() {
  for (let attempt = 1; attempt <= ATTEMPT_CAP; attempt++) {
    const numbers = drawNumbers(config.mainCount, config.mainPool);
    if (!excluded.has(canonical(numbers))) {
      return { numbers, powerball: randomInt(config.powerballPool), attempts: attempt };
    }
  }
  throw new Error('Could not find an unused combination within the attempt cap.');
}

/* ---------- maths for the honesty panel ---------- */

function combinations(n, k) {
  let result = 1;
  for (let i = 1; i <= k; i++) result = (result * (n - k + i)) / i;
  return Math.round(result);
}

function describeOdds() {
  const total = combinations(config.mainPool, config.mainCount);
  const remaining = total - excluded.size;
  const share = (excluded.size / total) * 100;

  el.spaceSize.textContent = nz.format(total);
  el.excludedShare.textContent = `${nz.format(excluded.size)} of them (${share.toFixed(3)}%)`;
  el.oddsBefore.textContent = `1 in ${nz.format(total)}`;
  el.oddsAfter.textContent = `1 in ${nz.format(remaining)}`;
}

/* ---------- rendering ---------- */

function renderLine({ numbers, powerball }) {
  // Main numbers and Powerball go on separate rows deliberately. Seven balls on
  // one row wraps unevenly on a phone; this reads the same at any width.
  const main = document.createElement('div');
  main.className = 'row main';
  main.append(...numbers.map((n, i) => ball(n, i)));

  const power = document.createElement('div');
  power.className = 'row power';
  power.append(ball(powerball, numbers.length, true));

  el.balls.replaceChildren(main, power);
}

function ball(value, index, isPowerball = false) {
  const node = document.createElement('span');
  node.className = isPowerball ? 'ball pb' : 'ball';
  node.textContent = value;
  node.style.animationDelay = `${index * 40}ms`;
  if (isPowerball) node.setAttribute('aria-label', `Powerball ${value}`);
  return node;
}

function renderReadout({ attempts }) {
  const checked = `Checked against ${nz.format(excluded.size)} past draws`;
  const redraws =
    attempts === 1
      ? 'first line was unused'
      : `redrawn ${attempts - 1} ${attempts === 2 ? 'time' : 'times'} to avoid a past winner`;
  el.readout.textContent = `${checked} — ${redraws}.`;
}

function renderHistory() {
  el.historyPanel.hidden = history.length === 0;
  el.history.replaceChildren(
    ...history.map((entry) => {
      const li = document.createElement('li');
      const line = document.createElement('span');
      line.className = 'line';
      line.textContent = entry.numbers.join('  ');
      const pb = document.createElement('span');
      pb.className = 'pb';
      pb.textContent = `PB ${entry.powerball}`;
      li.append(line, pb);
      return li;
    }),
  );
}

function renderDataBadge() {
  el.dataProvenance.textContent = config.synthetic
    ? `The comparison set is currently ${nz.format(excluded.size)} placeholder draws generated by tools/generate-synthetic-draws.mjs — the right shape and size for real NZ Lotto history, but not real results. Swapping in real data means replacing data/draws.json; no other code changes.`
    : `The comparison set is ${nz.format(excluded.size)} real draws, ${config.firstDraw} to ${config.lastDraw}.`;

  if (!config.synthetic) return;
  el.dataBadge.hidden = false;
  el.dataBadge.textContent =
    'Using placeholder draw data — the numbers below are generated correctly, but the "already won" set is synthetic, not real NZ Lotto history.';
}

/* ---------- fun facts ---------- */

// Every fact pairs an observation with what chance predicts for it. That
// pairing is the feature, not padding: a bare frequency table sitting next to a
// Generate button reads as a tip sheet, and this app's whole claim is that the
// machine has no memory. Nothing here is framed as due, hot or cold.
function renderFunFacts(draws) {
  const n = draws.length;
  const p = config.mainCount / config.mainPool;
  const expected = n * p;
  const sd = Math.sqrt(n * p * (1 - p));

  const freq = new Map();
  const pairs = new Map();
  const triplets = new Map();
  const lastSeen = new Map();
  const bump = (map, key) => map.set(key, (map.get(key) || 0) + 1);

  draws.forEach((draw, index) => {
    const s = draw.numbers;
    for (let i = 0; i < s.length; i += 1) {
      bump(freq, s[i]);
      lastSeen.set(s[i], index);
      for (let j = i + 1; j < s.length; j += 1) {
        bump(pairs, `${s[i]} & ${s[j]}`);
        for (let k = j + 1; k < s.length; k += 1) bump(triplets, `${s[i]}, ${s[j]} & ${s[k]}`);
      }
    }
  });

  const ranked = (map) => [...map.entries()].sort((a, b) => b[1] - a[1]);
  const counts = ranked(freq);
  const [hiN, hiC] = counts[0];
  const [loN, loC] = counts[counts.length - 1];
  const withinTwo = counts.filter(([, c]) => Math.abs(c - expected) <= 2 * sd).length;

  const [pairKey, pairCount] = ranked(pairs)[0];
  const pairSpace = combinations(config.mainPool, 2);
  const [tripKey, tripCount] = ranked(triplets)[0];
  const tripSpace = combinations(config.mainPool, 3);

  const [waitN, waitDraws] = [...lastSeen.entries()]
    .map(([ball, index]) => [ball, n - 1 - index])
    .sort((a, b) => b[1] - a[1])[0];

  const space = combinations(config.mainPool, config.mainCount);
  const repeats = n - new Set(draws.map((draw) => canonical(draw.numbers))).size;

  const facts = [
    [
      `${hiN} leads ${loN} by ${hiC - loC} — and that is less of a gap than chance usually manages`,
      `${hiN} has come up ${hiC} times, ${loN} only ${loC}. Across ${nz.format(n)} draws every number is expected about ${Math.round(expected)} times, with a normal spread of roughly ${Math.round(sd)} either side. ${withinTwo === counts.length ? `All ${counts.length}` : `${withinTwo} of the ${counts.length}`} numbers land within two of those — the signature of nothing happening.`,
    ],
    [
      `${pairKey} is the most frequent pairing, ${pairCount} times`,
      `There are ${nz.format(pairSpace)} possible pairs and the average one appears about ${Math.round((n * combinations(config.mainCount, 2)) / pairSpace)} times. Some pair has to lead, and the leader of a long list always sits well above the average. That is arithmetic, not affinity.`,
    ],
    [
      `${tripKey} is the most frequent trio, ${tripCount} times`,
      `Out of ${nz.format(tripSpace)} possible trios, averaging about ${((n * combinations(config.mainCount, 3)) / tripSpace).toFixed(1)} appearances each. The more combinations you look across, the further ahead the front-runner gets by luck alone.`,
    ],
    [
      `${waitN} has not appeared for ${waitDraws} draws`,
      `Its chance in the next draw is ${Math.round(p * 100)}% — the same as every other number's, and the same as it was ${waitDraws} draws ago. A ball that has been skipped is not owed anything.`,
    ],
    [
      repeats === 0
        ? `Not one combination has ever repeated in ${nz.format(n)} draws`
        : `${repeats} combination${repeats === 1 ? ' has' : 's have'} come up twice in ${nz.format(n)} draws`,
      `Less surprising than it sounds: these draws cover ${((n / space) * 100).toFixed(3)}% of the ${nz.format(space)} possible lines. That tiny share is exactly why skipping them barely moves the odds.`,
    ],
  ];

  el.funFacts.replaceChildren(
    ...facts.map(([headline, why]) => {
      const li = document.createElement('li');
      const b = document.createElement('b');
      b.textContent = headline;
      const span = document.createElement('span');
      span.textContent = why;
      li.append(b, span);
      return li;
    }),
  );

  let host = null;
  try {
    host = new URL(config.source).host;
  } catch {
    /* older datasets carry no source; the sentence just omits it */
  }
  el.factsSource.textContent = host
    ? `Draw history from ${host}, covering ${config.firstDraw} to ${config.lastDraw}. The counts above are worked out from that history by this app, not taken from the site.`
    : `Counted from the loaded draw history, ${config.firstDraw} to ${config.lastDraw}.`;
}

/* ---------- history persistence ---------- */

function loadHistory() {
  try {
    const raw = localStorage.getItem(HISTORY_KEY);
    return raw ? JSON.parse(raw) : [];
  } catch {
    return []; // private mode, or a stale shape from an older version
  }
}

function saveHistory() {
  try {
    localStorage.setItem(HISTORY_KEY, JSON.stringify(history));
  } catch {
    /* not worth interrupting the user over */
  }
}

/* ---------- wiring ---------- */

function onGenerate() {
  let line;
  try {
    line = generateLine();
  } catch (error) {
    el.readout.textContent = error.message;
    return;
  }

  el.placeholder?.remove();
  renderLine(line);
  renderReadout(line);

  history = [{ numbers: line.numbers, powerball: line.powerball }, ...history].slice(0, MAX_HISTORY);
  saveHistory();
  renderHistory();
}

async function init() {
  renderHistory();

  try {
    const response = await fetch('./data/draws.json');
    if (!response.ok) throw new Error(`HTTP ${response.status}`);
    const payload = await response.json();

    config = payload.meta;
    excluded = new Set(payload.draws.map((draw) => canonical(draw.numbers)));

    describeOdds();
    renderDataBadge();
    renderFunFacts(payload.draws);

    el.generate.disabled = false;
    el.generate.textContent = 'Generate a line';
    el.generate.addEventListener('click', onGenerate);
  } catch (error) {
    el.generate.textContent = 'Draw data unavailable';
    el.readout.textContent = `Could not load the past-draw set (${error.message}). Generating without it would defeat the point, so the button stays disabled.`;
  }

  el.clearHistory.addEventListener('click', () => {
    history = [];
    saveHistory();
    renderHistory();
  });

  const showOffline = () => {
    el.offline.hidden = navigator.onLine;
  };
  addEventListener('online', showOffline);
  addEventListener('offline', showOffline);
  showOffline();

  if ('serviceWorker' in navigator) {
    // Relative path so the scope follows the deploy path — this app is served
    // from a subdirectory on GitHub Pages, not a domain root.
    navigator.serviceWorker.register('./sw.js').catch(() => {
      /* app works fine without offline support */
    });
  }
}

init();
